context.sessions.rules = [
    { matches = [ { application.name = "aero-shell" } ] actions = { node.latency = 16 } }
    { matches = [ { application.name = "aero-settings" } ] actions = { node.latency = 16 } }
    { matches = [ { application.name = "pipewire" } ] actions = { node.latency = 32 } }
]
