#!/bin/sh
if [ -x /usr/local/bin/aero-lock-gtk ] && command -v python3 >/dev/null 2>&1; then
    exec /usr/local/bin/aero-lock-gtk "$@"
fi
[ -x /usr/local/bin/aero-lock.elf ] && exec /usr/local/bin/aero-lock.elf "$@"
exec /usr/local/bin/aero-lock-lite "$@"
